eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9020/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
server:
  port: 9030
spring:
  application:
    name: core-service
  #normalde buras? 0 olmal? her instance i?in otomatik port atamas? yapar
#spring:
#  application:
#    name: order-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/crmTurkcellOrderdb
#    username: postgres
#    password: 12345
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#      javax:
#        persistence:
#          validation:
#            mode: none
#    show-sql: true
#